### ISSUE TITLE
Planned Features Roadmap

### ISSUE THREAD

**Issue by Enchanted-Games** [Enchanted-Games/block-place-particles#6]
# Planned Features
This list shows what features are planned to be added in roughly what mod version, this is subject to change and features may be added or removed. Features can be discussed or suggested below

## v0.1
- [x] Particles when placing blocks
- [x] Particles when placing fluids
- [x] Unique block breaking/placement particles for snow blocks and all types of vanilla leaves

## v0.2
- [x] Campfires emit sparks
- [ ] Fire emits sparks

(the following are based on #4)
- [ ] (done but needs polishing) Sparks when minecarts are traveling on rails
- [x] Flint and Steel create sparks when used
- [ ] Fire charge emits smoke / fire when used
- [ ] Grindstones, Anvils, and stonecutters, create spark particles when something is crafted.
- [ ] Bubbles when collidable blocks are placed underwater 

## v0.3
- [ ] Block specific particles should emit when cracking a block or sprinting / falling on a block
- [ ] More block specific particle types (e.g: blades of grass, dust for dusty blocks like sand)
- [ ] Particles when stripping a log
- [ ] Particles when tilling dirt
- [ ] Rework block specific particles to directly use blocks instead of blockitems internally

## v0.4
(the following are based on #4)
- [ ] Shooting stars rarely speed across the sky at night
- [ ] Lightning striking blocks creates spark effects
- [ ] Players create a trail of footprints behind them (Can toggle this for other entities as well)

**Comment by Mitrays** [comment]
You removed fireflies?

**Comment by Enchanted-Games** [comment]
> You removed fireflies?

Yes, I don’t think it really fits with the idea of this mod (at least not in the way i was going to implement them to begin with), and there’s already a lot of other mods that add them

**Comment by Mitrays** [comment]
I like the new update so much! And the bubble popping effect on lava seems interesting. Can't wait to see how you implement this!

**Comment by Russeki** [comment]
Haven't tried the mod yet but you got my attention with your throughout future update organization.

**Comment by Enchanted-Games** [comment]
> Haven't tried the mod yet but you got my attention with your throughout future update organization.

It’s my first time actually planning out features for a mod, it’s really helped me keep motivated to work on it (as opposed to what I used to do and just add random features whenever I felt like it). It also lets me make somewhat regular updates while giving myself time to work on other stuff to not get burned out

**Comment by Enchanted-Games** [comment]
Please see my comments on #51 and #49 , backports are off the table for now
